export const GET_STARTGAME_NOD='GET_STARTGAME_NOD'
export const GET_TIMER= 'GET_TIMER';
export const GET_CLICK_COUNT='GET_CLICK_COUNT';
export const GET_GAMEOVER_STATUS='GET_GAMEOVER_STATUS';
export const GET_WINNER_STATUS='GET_WINNER_STATUS';
export const TIMEOVER_STATUS='TIMEOVER_STATUS'
